### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by dinotheextinct** [redmcg/wine-mono#1]
`wineserver: using server-side synchronization.
0024:fixme:file:NtLockFile I/O completion on lock not implemented yet
0024:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
00b4:fixme:file:NtLockFile I/O completion on lock not implemented yet
00b4:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
00bc:err:setupapi:create_dest_file failed to create L"C:\\windows\\Microsoft.NET\\Framework\\v1.1.4322\\aspnet_regiis.exe" (error=80)
00bc:err:setupapi:create_dest_file failed to create L"C:\\windows\\Microsoft.NET\\Framework\\v1.1.4322\\ngen.exe" (error=80)
00bc:err:setupapi:create_dest_file failed to create L"C:\\windows\\Microsoft.NET\\Framework\\v1.1.4322\\fusion.dll" (error=80)
00bc:err:setupapi:create_dest_file failed to create L"C:\\windows\\Microsoft.NET\\Framework\\v1.1.4322\\mscorwks.dll" (error=80)
00bc:err:setupapi:create_dest_file failed to create L"C:\\windows\\Microsoft.NET\\Framework\\v1.1.4322\\regsvcs.exe" (error=80)
00bc:err:setupapi:create_dest_file failed to create L"C:\\windows\\Microsoft.NET\\Framework\\v2.0.50727\\ngen.exe" (error=80)
00bc:err:setupapi:create_dest_file failed to create L"C:\\windows\\Microsoft.NET\\Framework\\v2.0.50727\\fusion.dll" (error=80)
00bc:err:setupapi:create_dest_file failed to create L"C:\\windows\\Microsoft.NET\\Framework\\v2.0.50727\\mscorwks.dll" (error=80)
00bc:err:setupapi:create_dest_file failed to create L"C:\\windows\\Microsoft.NET\\Framework\\v2.0.50727\\regasm.exe" (error=80)
00bc:err:setupapi:create_dest_file failed to create L"C:\\windows\\Microsoft.NET\\Framework\\v3.0\\windows communication foundation\\servicemodelreg.exe" (error=80)
00bc:err:setupapi:create_dest_file failed to create L"C:\\windows\\Microsoft.NET\\Framework\\v3.0\\wpf\\presentationfontcache.exe" (error=80)
00bc:err:setupapi:create_dest_file failed to create L"C:\\windows\\Microsoft.NET\\Framework\\v4.0.30319\\ngen.exe" (error=80)
00bc:err:setupapi:create_dest_file failed to create L"C:\\windows\\Microsoft.NET\\Framework\\v4.0.30319\\fusion.dll" (error=80)
00c4:err:setupapi:create_dest_file failed to create L"C:\\windows\\Microsoft.NET\\Framework64\\v1.1.4322\\aspnet_regiis.exe" (error=80)
00c4:err:setupapi:create_dest_file failed to create L"C:\\windows\\Microsoft.NET\\Framework64\\v1.1.4322\\ngen.exe" (error=80)
00c4:err:setupapi:create_dest_file failed to create L"C:\\windows\\Microsoft.NET\\Framework64\\v1.1.4322\\fusion.dll" (error=80)
00c4:err:setupapi:create_dest_file failed to create L"C:\\windows\\Microsoft.NET\\Framework64\\v1.1.4322\\mscorwks.dll" (error=80)
00c4:err:setupapi:create_dest_file failed to create L"C:\\windows\\Microsoft.NET\\Framework64\\v1.1.4322\\regsvcs.exe" (error=80)
00c4:err:setupapi:create_dest_file failed to create L"C:\\windows\\Microsoft.NET\\Framework64\\v2.0.50727\\ngen.exe" (error=80)
00c4:err:setupapi:create_dest_file failed to create L"C:\\windows\\Microsoft.NET\\Framework64\\v2.0.50727\\fusion.dll" (error=80)
00c4:err:setupapi:create_dest_file failed to create L"C:\\windows\\Microsoft.NET\\Framework64\\v2.0.50727\\mscorwks.dll" (error=80)
00c4:err:setupapi:create_dest_file failed to create L"C:\\windows\\Microsoft.NET\\Framework64\\v2.0.50727\\regasm.exe" (error=80)
00c4:err:setupapi:create_dest_file failed to create L"C:\\windows\\Microsoft.NET\\Framework64\\v3.0\\windows communication foundation\\servicemodelreg.exe" (error=80)
00c4:err:setupapi:create_dest_file failed to create L"C:\\windows\\Microsoft.NET\\Framework64\\v3.0\\wpf\\presentationfontcache.exe" (error=80)
00c4:err:setupapi:create_dest_file failed to create L"C:\\windows\\Microsoft.NET\\Framework64\\v4.0.30319\\ngen.exe" (error=80)
00c4:err:setupapi:create_dest_file failed to create L"C:\\windows\\Microsoft.NET\\Framework64\\v4.0.30319\\fusion.dll" (error=80)
00b4:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 5)
00b4:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 5)
0024:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 5)
0024:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 5)
`

**Comment by redmcg** [comment]
@dinotheextinct Thanks for the report.

There's a new version and I've also updated the wiki with new instructions for installation using protontricks:
https://github.com/redmcg/wine-mono/wiki#with-protontricks

Can you give the new version a go and follow the new installation process (assuming you used protontricks last time).

Let me know if this resolves the issue. If not, maybe give a few more details about what happens (i.e. is there an error pop-ups or does the game just silently close).

Thanks again.

**Comment by redmcg** [comment]
Closing due to evident extinction
