### ISSUE TITLE
Wiki instructions missing a step 

### ISSUE THREAD

**Issue by alasky17** [redmcg/wine-mono#7]
I happened to notice that in the wiki instructions here: https://github.com/redmcg/wine-mono/wiki#manually you forgot to mention that the old wine-mono version needs to be manually installed first via remove_mono or some other method.  When I followed the instructions as-written, I ended up with both the old and new mono versions in the prefix.  Probably most folks can figure this out, but I just wanted to let you know :)

**Comment by kakra** [comment]
> needs to be manually installed

... "uninstalled" probably? ;-)

**Comment by redmcg** [comment]
Hi @alasky17 :wave: . Fancy meeting you here. The install program should uninstall any previous version, but I've updated the Wiki recommending folks double check the old version was uninstalled correctly. Thanks for taking an interest in this humble Wiki.
